# Generated by Django 3.2.6 on 2021-08-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feets', '0003_auto_20210823_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobisGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Knee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('feet_image', models.ImageField(blank=True, upload_to='')),
                ('feet', models.ManyToManyField(null=True, related_name='knees', to='feets.Feet')),
                ('mobis_grade', models.ManyToManyField(null=True, related_name='Knees', to='knees.MobisGrade')),
                ('type', models.ManyToManyField(null=True, related_name='knee', to='knees.Type')),
            ],
        ),
    ]
