# Generated by Django 3.2.6 on 2021-09-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0004_auto_20210910_0455'),
        ('knees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knee',
            name='feet',
            field=models.ManyToManyField(related_name='knees', to='feets.Feet'),
        ),
        migrations.AlterField(
            model_name='knee',
            name='feet_image',
            field=models.ImageField(blank=True, upload_to='knees'),
        ),
        migrations.AlterField(
            model_name='knee',
            name='mobis_grade',
            field=models.ManyToManyField(related_name='Knees', to='knees.MobisGrade'),
        ),
        migrations.AlterField(
            model_name='knee',
            name='type',
            field=models.ManyToManyField(related_name='knees', to='knees.Type'),
        ),
    ]
