# Generated by Django 3.2.6 on 2022-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knees', '0002_auto_20210910_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Waterproof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='knee',
            name='feet',
        ),
        migrations.RemoveField(
            model_name='knee',
            name='feet_image',
        ),
        migrations.RemoveField(
            model_name='knee',
            name='type',
        ),
        migrations.AddField(
            model_name='knee',
            name='knee_image',
            field=models.ImageField(blank=True, upload_to='knees'),
        ),
        migrations.AlterField(
            model_name='knee',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='knee',
            name='mobis_grade',
            field=models.ManyToManyField(blank=True, related_name='knees', to='knees.MobisGrade'),
        ),
        migrations.AlterField(
            model_name='knee',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='knee',
            name='activity',
            field=models.ManyToManyField(blank=True, related_name='knees', to='knees.Activity'),
        ),
        migrations.AddField(
            model_name='knee',
            name='age',
            field=models.ManyToManyField(blank=True, related_name='knees', to='knees.Age'),
        ),
        migrations.AddField(
            model_name='knee',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='knees', to='knees.Brand'),
        ),
        migrations.AddField(
            model_name='knee',
            name='function',
            field=models.ManyToManyField(blank=True, related_name='knees', to='knees.Function'),
        ),
        migrations.AddField(
            model_name='knee',
            name='hope',
            field=models.ManyToManyField(blank=True, related_name='knees', to='knees.Hope'),
        ),
        migrations.AddField(
            model_name='knee',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='knees', to='knees.Rating'),
        ),
        migrations.AddField(
            model_name='knee',
            name='waterproof',
            field=models.ManyToManyField(blank=True, related_name='knees', to='knees.Waterproof'),
        ),
        migrations.AddField(
            model_name='knee',
            name='weight',
            field=models.ManyToManyField(blank=True, related_name='knees', to='knees.Weight'),
        ),
    ]
