# Generated by Django 3.2.6 on 2021-08-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0002_alter_feet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feet',
            name='mobis_grade',
            field=models.ManyToManyField(null=True, related_name='feets', to='feets.MobisGrade'),
        ),
        migrations.AlterField(
            model_name='feet',
            name='type',
            field=models.ManyToManyField(null=True, related_name='feets', to='feets.Type'),
        ),
    ]
