# Generated by Django 3.2.6 on 2021-09-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0003_auto_20210823_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feet',
            name='mobis_grade',
            field=models.ManyToManyField(related_name='feets', to='feets.MobisGrade'),
        ),
        migrations.AlterField(
            model_name='feet',
            name='type',
            field=models.ManyToManyField(related_name='feets', to='feets.Type'),
        ),
    ]
