# Generated by Django 3.2.6 on 2021-09-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0005_alter_feet_feet_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Motion',
        ),
        migrations.RemoveField(
            model_name='feet',
            name='type',
        ),
        migrations.AddField(
            model_name='feet',
            name='motion',
            field=models.ManyToManyField(related_name='feets', to='feets.Motion'),
        ),
    ]
