# Generated by Django 3.2.6 on 2021-09-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0006_auto_20210922_0314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motion',
            new_name='Weight',
        ),
        migrations.RemoveField(
            model_name='feet',
            name='motion',
        ),
        migrations.AddField(
            model_name='feet',
            name='weight',
            field=models.ManyToManyField(related_name='feets', to='feets.Weight'),
        ),
    ]
