# Generated by Django 3.2.6 on 2021-11-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0009_auto_20211110_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='feet',
            name='height',
            field=models.ManyToManyField(related_name='feets', to='feets.Height'),
        ),
        migrations.AddField(
            model_name='feet',
            name='age',
            field=models.ManyToManyField(related_name='feets', to='feets.Age'),
        ),
    ]
