# Generated by Django 3.2.6 on 2021-11-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0010_auto_20211110_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='feet',
            name='foot_size',
            field=models.ManyToManyField(related_name='feets', to='feets.FootSize'),
        ),
    ]
