# Generated by Django 3.2.6 on 2021-12-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0012_auto_20211110_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feet',
            name='activity',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.Activity'),
        ),
        migrations.AlterField(
            model_name='feet',
            name='age',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.Age'),
        ),
        migrations.AlterField(
            model_name='feet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feet',
            name='foot_size',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.FootSize'),
        ),
        migrations.AlterField(
            model_name='feet',
            name='height',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.Height'),
        ),
        migrations.AlterField(
            model_name='feet',
            name='mobis_grade',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.MobisGrade'),
        ),
        migrations.AlterField(
            model_name='feet',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='feet',
            name='step_count',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.StepCount'),
        ),
        migrations.AlterField(
            model_name='feet',
            name='weight',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.Weight'),
        ),
    ]
