# Generated by Django 3.2.6 on 2021-12-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0013_auto_20211207_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='feet',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='feets.Rating'),
        ),
    ]
