# Generated by Django 3.2.6 on 2021-12-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0014_auto_20211209_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feet',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.Rating'),
        ),
    ]
