# Generated by Django 3.2.6 on 2021-12-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0015_alter_feet_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FootSize',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='StepCount',
            new_name='Function',
        ),
        migrations.RenameModel(
            old_name='Height',
            new_name='Traffic',
        ),
        migrations.RemoveField(
            model_name='feet',
            name='foot_size',
        ),
        migrations.RemoveField(
            model_name='feet',
            name='height',
        ),
        migrations.RemoveField(
            model_name='feet',
            name='step_count',
        ),
        migrations.AddField(
            model_name='feet',
            name='Function',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.Function'),
        ),
        migrations.AddField(
            model_name='feet',
            name='Traffic',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.Traffic'),
        ),
        migrations.AddField(
            model_name='feet',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.Brand'),
        ),
    ]
