# Generated by Django 3.2.6 on 2021-12-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0017_auto_20211229_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waterproof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='feet',
            name='waterproof',
        ),
        migrations.AddField(
            model_name='feet',
            name='waterproof',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.Waterproof'),
        ),
    ]
