# Generated by Django 3.2.6 on 2022-01-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feets', '0018_auto_20211229_0924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Traffic',
            new_name='Hope',
        ),
        migrations.RemoveField(
            model_name='feet',
            name='traffic',
        ),
        migrations.AddField(
            model_name='feet',
            name='hope',
            field=models.ManyToManyField(blank=True, related_name='feets', to='feets.Hope'),
        ),
    ]
