# Generated by Django 3.2.6 on 2021-12-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20211126_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workshop',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
